package com.group11.accord.api.user;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Size;
import lombok.NonNull;

public record SessionCredentials (

        @NonNull
        @Schema(description = "The accounts id")
        Long id,

        @NonNull
        @Schema(description = "The session token. Note: uniquely generated each time an account is logged in")
        @Size(max = 64, min = 64, message = "Token must be exactly 64 characters long as it is generated by the server and cannot be changed")
        String token

) { }
